# Generated by Django 5.0.6 on 2024-07-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Colaborator',
        ),
    ]
