# Generated by Django 5.0.6 on 2024-07-07 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_colaborator_birth_date_colaborator_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('cpf', models.CharField(default='00000000000', max_length=11, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Colaborator',
        ),
    ]
